import { useEffect, useMemo, useRef, useState } from 'react'
import { Activity, Archive, ArrowLeft, ArrowRight, BarChart3, Bell, BookOpen, CalendarDays, Check, ChevronDown, CircleHelp, ClipboardList, Download, FileText, GraduationCap, HeartHandshake, Home, LockKeyhole, LogOut, Menu, Moon, Plus, Search, Settings, ShieldCheck, Sun, Upload, Users, X, type LucideIcon } from 'lucide-react'
import { client, csv, dateLabel, domains, download, kinds, today, uid, bkProjectUrl, bkPublishableKey, registrationAuthorization, type Case, type Membership, type RecordItem, type Student } from './data'
import type { User } from '@supabase/supabase-js'

type Tab='dashboard'|'students'|'cases'|'analytics'|'reports'|'settings'|string
type Modal='student'|'case'|'record'|'school'|'invite'|null
const nav:{title:string;items:[string,string,LucideIcon][]}[]=[
  {title:'Workspace',items:[['dashboard','Beranda',Home],['students','Siswa 360°',Users],['cases','Kasus & asesmen',ShieldCheck]]},
  {title:'Layanan BK',items:[['need','Pemetaan kebutuhan',Activity],['counseling','Konseling individu',HeartHandshake],['group','Konseling kelompok',Users],['classical','Layanan klasikal',BookOpen],['rpl','RPL layanan',FileText],['program','Program BK',ClipboardList],['agenda','Agenda',CalendarDays]]},
  {title:'Tindak lanjut',items:[['followup','Tindak lanjut',Check],['visit','Kunjungan rumah',Home],['referral','Rujukan',ArrowRight],['career','Perencanaan karier',GraduationCap]]},
  {title:'Kelola',items:[['document','Dokumen',FileText],['analytics','Analitik',BarChart3],['reports','Laporan',Download],['settings','Pengaturan',Settings]]}
]
const fieldMap:Record<string,{label:string;key:string;placeholder?:string}[]>={
  need:[{label:'Sumber informasi',key:'source'},{label:'Kebutuhan / masalah',key:'issue'}],
  counseling:[{label:'Komponen layanan',key:'component'},{label:'Rencana sesi berikutnya',key:'next_date'}],
  group:[{label:'Kelas sasaran',key:'class_target'},{label:'NIS peserta (pisahkan koma)',key:'participants'}],
  classical:[{label:'Kelas sasaran',key:'class_target'},{label:'Metode',key:'method'},{label:'Media',key:'media'},{label:'Jumlah hadir',key:'attendance'}],
  rpl:[{label:'Tujuan layanan',key:'goal'},{label:'Metode',key:'method'},{label:'Media',key:'media'},{label:'Evaluasi',key:'evaluation'}],
  program:[{label:'Sasaran',key:'target'},{label:'Indikator keberhasilan',key:'indicator'}],
  agenda:[{label:'Waktu',key:'time'},{label:'Lokasi',key:'location'}],
  followup:[{label:'Jenis tindak lanjut',key:'action'},{label:'Pihak terkait',key:'parties'},{label:'Tanggal evaluasi',key:'next_date'}],
  visit:[{label:'Tujuan kunjungan',key:'goal'},{label:'Hasil kunjungan',key:'result'}],
  referral:[{label:'Tujuan rujukan',key:'destination'},{label:'Pihak terkait',key:'parties'}],
  career:[{label:'Minat siswa',key:'interests'},{label:'Rencana studi/karier',key:'plan'}],
  document:[{label:'Jenis dokumen',key:'document_type'},{label:'Tautan dokumen (akses terbatas)',key:'url'}]
}
const idName=(id:string|null,students:Student[])=>students.find(s=>s.id===id)?.name||'Umum / kelompok'
const initialStudent={nis:'',name:'',class_name:'',gender:'L',guardian_name:'',guardian_phone:'',status:'Aktif'}
const initialCase={student_id:'',opened_on:today(),domain:'Sosial',topic:'',priority:'Sedang',source:'',status:'Berjalan',summary:'',next_on:''}
const initialRecord={student_id:'',case_id:'',happened_on:today(),title:'',domain:'Pribadi',status:'Terencana',notes:'',confidential:false,details:{} as Record<string,string>}

export default function App(){
  const [user,setUser]=useState<User|null>(null),[boot,setBoot]=useState(true),[demo,setDemo]=useState(false)
  const [membership,setMembership]=useState<Membership|null>(null),[students,setStudents]=useState<Student[]>([]),[cases,setCases]=useState<Case[]>([]),[records,setRecords]=useState<RecordItem[]>([])
  const [remoteReport,setRemoteReport]=useState<{students:number;cases:number;completed:number;sessions:number;services:number;domains:Record<string,number>}|null>(null)
  const [tab,setTab]=useState<Tab>('dashboard'),[modal,setModal]=useState<Modal>(null),[editId,setEditId]=useState<string|null>(null),[selected,setSelected]=useState<Student|null>(null)
  const [studentForm,setStudentForm]=useState(initialStudent),[caseForm,setCaseForm]=useState(initialCase),[recordForm,setRecordForm]=useState(initialRecord)
  const [schoolName,setSchoolName]=useState(''),[academicYear,setAcademicYear]=useState('2026/2027'),[inviteEmail,setInviteEmail]=useState(''),[inviteRole,setInviteRole]=useState('counselor'),[inviteToken,setInviteToken]=useState(''),[claimToken,setClaimToken]=useState('')
  const [search,setSearch]=useState(''),[classFilter,setClassFilter]=useState('Semua kelas'),[statusFilter,setStatusFilter]=useState('Aktif'),[toast,setToast]=useState(''),[busy,setBusy]=useState(false)
  const [sidebar,setSidebar]=useState(false),[theme,setTheme]=useState(localStorage.getItem('bk-theme')||'light'),[authEmail,setAuthEmail]=useState(''),[authPassword,setAuthPassword]=useState(''),[authMode,setAuthMode]=useState<'login'|'register'>('login')
  const importRef=useRef<HTMLInputElement>(null)
  const flash=(message:string)=>{setToast(message);setTimeout(()=>setToast(''),5000)}
  useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('bk-theme',theme)},[theme])
  useEffect(()=>{if(!client){setBoot(false);return}client.auth.getUser().then(({data})=>{setUser(data.user);setBoot(false)});const {data:{subscription}}=client.auth.onAuthStateChange((_event,session)=>setUser(session?.user??null));return()=>subscription.unsubscribe()},[])
  const refresh=async(current=user)=>{
    if(!client||!current)return
    const {data:members,error}=await client.from('memberships').select('school_id,user_id,role,display_name,school:schools(name,academic_year)').eq('user_id',current.id).limit(1)
    if(error){flash(error.message);return}
    const member=(members?.[0]||null) as unknown as Membership|null;setMembership(member)
    if(!member){setStudents([]);setCases([]);setRecords([]);setRemoteReport(null);return}
    // Principal may only request aggregate statistics; never query student or case detail.
    if(member.role==='principal'){
      setStudents([]);setCases([]);setRecords([])
      const {data,error:reportError}=await client.rpc('bk_school_report',{p_school:member.school_id})
      if(reportError){setRemoteReport(null);flash(reportError.message)}
      else setRemoteReport(data as typeof remoteReport)
      return
    }
    const pageSchool=async(table:'students'|'bk_cases'|'bk_records',order:string,ascending=false)=>{
      const out:any[]=[];let offset=0
      while(true){
        const {data,error}=await client.from(table).select('*').eq('school_id',member.school_id)
          .order(order,{ascending}).range(offset,offset+999)
        if(error)throw error
        out.push(...(data||[]))
        if((data||[]).length<1000)break
        offset+=1000
      }
      return out
    }
    try{
      const [studentRows,caseRows,recordRows,d]=await Promise.all([
        pageSchool('students','name',true),
        pageSchool('bk_cases','opened_on'),
        pageSchool('bk_records','happened_on'),
        client.rpc('bk_school_report',{p_school:member.school_id})
      ])
      setStudents(studentRows as Student[]);setCases(caseRows as Case[]);setRecords(recordRows as RecordItem[])
      if(d.error){setRemoteReport(null);flash(d.error.message)}else setRemoteReport(d.data as typeof remoteReport)
    }catch(e:any){flash(e?.message||'Data sekolah belum berhasil dimuat. Coba muat ulang.')}
  }
  useEffect(()=>{if(user)void refresh(user);else{setMembership(null);setStudents([]);setCases([]);setRecords([]);setRemoteReport(null);setTab('dashboard');setSelected(null)}},[user?.id])
  const activeCases=cases.filter(c=>c.status!=='Selesai'&&c.status!=='Arsip')
  const due=records.filter(r=>r.kind==='followup'&&r.status!=='Selesai'&&r.details?.next_date&&r.details.next_date<=today()).length+cases.filter(c=>c.next_on&&c.next_on<=today()&&c.status==='Berjalan').length
  const classes=Array.from(new Set(students.map(s=>s.class_name))).filter(Boolean).sort()
  const shownStudents=students.filter(s=>(statusFilter==='Semua'||s.status===statusFilter)&&(classFilter==='Semua kelas'||s.class_name===classFilter)&&`${s.name} ${s.nis} ${s.class_name}`.toLowerCase().includes(search.toLowerCase()))
  const visibleCases=cases.filter(c=>`${c.code} ${c.topic} ${idName(c.student_id,students)}`.toLowerCase().includes(search.toLowerCase()))
  const visibleRecords=records.filter(r=>r.kind===tab&&`${r.title} ${idName(r.student_id,students)}`.toLowerCase().includes(search.toLowerCase()))
  const tabName=nav.flatMap(g=>g.items).find(i=>i[0]===tab)?.[1]||'Beranda'
  const role=membership?.role||'owner',isManager=role==='owner'||role==='admin'
  const canEdit=role==='owner'||role==='admin'||role==='counselor'
  const school=membership?.school?.name||'Sekolah Anda'

  async function auth(e:React.FormEvent){e.preventDefault();if(!client)return;setBusy(true);try{if(authMode==='register'){const response=await fetch(`${bkProjectUrl}/functions/v1/register`,{method:'POST',headers:{'Content-Type':'application/json',apikey:bkPublishableKey,Authorization:`Bearer ${registrationAuthorization}`},body:JSON.stringify({email:authEmail,password:authPassword})});const result=await response.json();if(!response.ok){flash(result.error||'Pendaftaran gagal.');return}}const {error}=await client.auth.signInWithPassword({email:authEmail,password:authPassword});if(error)flash(error.message);else flash(authMode==='register'?'Akun aktif. Selamat datang di BK Pro.':'Berhasil masuk.')}catch{flash('Koneksi gagal. Coba lagi.')}finally{setBusy(false)}}
  async function createSchool(e:React.FormEvent){e.preventDefault();if(!client||!user||busy)return;setBusy(true);try{
    const {error}=await client.rpc('create_bk_school',{p_name:schoolName.trim(),p_academic_year:academicYear.trim()});
    if(error){flash(error.message);return}
    setModal(null);await refresh(user);flash('Workspace sekolah siap digunakan.')
  }catch{flash('Ruang kerja belum berhasil dibuat. Coba lagi.')}finally{setBusy(false)}}
  async function saveStudent(e:React.FormEvent){e.preventDefault();if(!membership)return;setBusy(true);const payload={...studentForm,school_id:membership.school_id,nis:studentForm.nis.trim(),name:studentForm.name.trim(),counselor_id:editId?(students.find(x=>x.id===editId)?.counselor_id??user?.id??null):(user?.id??null)};if(demo){const item={...payload,id:editId||uid(),created_at:new Date().toISOString()};setStudents(p=>editId?p.map(x=>x.id===editId?item:x):[...p,item]);done('Data siswa tersimpan.');return}const q=editId?client!.from('students').update(payload).eq('id',editId):client!.from('students').insert(payload);const {error}=await q;setBusy(false);if(error)flash(error.message);else{void refresh();done('Data siswa tersimpan.')}}
  async function saveCase(e:React.FormEvent){e.preventDefault();if(!membership||!user)return;setBusy(true);const payload={...caseForm,school_id:membership.school_id,counselor_id:user.id,next_on:caseForm.next_on||null,code:editId?cases.find(x=>x.id===editId)?.code:`BK-${today().slice(2).replaceAll('-','')}-${Math.random().toString(36).slice(2,6).toUpperCase()}`};if(demo){const item={...payload,id:editId||uid(),created_at:new Date().toISOString()} as Case;setCases(p=>editId?p.map(x=>x.id===editId?item:x):[item,...p]);done('Kasus tersimpan.');return}const q=editId?client!.from('bk_cases').update(payload).eq('id',editId):client!.from('bk_cases').insert(payload);const {error}=await q;setBusy(false);if(error)flash(error.message);else{void refresh();done('Kasus tersimpan.')}}
  async function saveRecord(e:React.FormEvent){e.preventDefault();if(!membership||!user)return;setBusy(true);const payload={...recordForm,school_id:membership.school_id,counselor_id:user.id,student_id:recordForm.student_id||null,case_id:recordForm.case_id||null,kind:tab,confidential:tab==='counseling'||tab==='visit'||recordForm.confidential};if(demo){const item={...payload,id:editId||uid(),created_at:new Date().toISOString()};setRecords(p=>editId?p.map(x=>x.id===editId?item:x):[item,...p]);done('Catatan tersimpan.');return}const q=editId?client!.from('bk_records').update(payload).eq('id',editId):client!.from('bk_records').insert(payload);const {error}=await q;setBusy(false);if(error)flash(error.message);else{void refresh();done('Catatan tersimpan.')}}
  function done(message:string){setBusy(false);setModal(null);setEditId(null);flash(message)}
  function openNew(kind:Modal){setEditId(null);setModal(kind);setInviteToken('');setStudentForm(initialStudent);setCaseForm({...initialCase,student_id:selected?.id||''});setRecordForm({...initialRecord,student_id:selected?.id||''})}
  function editStudent(s:Student){setEditId(s.id);setStudentForm({nis:s.nis,name:s.name,class_name:s.class_name,gender:s.gender,guardian_name:s.guardian_name,guardian_phone:s.guardian_phone,status:s.status});setModal('student')}
  function editCase(c:Case){setEditId(c.id);setCaseForm({student_id:c.student_id,opened_on:c.opened_on,domain:c.domain,topic:c.topic,priority:c.priority,source:c.source,status:c.status,summary:c.summary,next_on:c.next_on||''});setModal('case')}
  function editRecord(r:RecordItem){setEditId(r.id);setRecordForm({student_id:r.student_id||'',case_id:r.case_id||'',happened_on:r.happened_on,title:r.title,domain:r.domain,status:r.status,notes:r.notes,confidential:r.confidential,details:r.details||{}});setModal('record')}
  async function archiveStudent(s:Student){if(!confirm(`Arsipkan ${s.name}? Riwayat layanan tetap tersimpan.`))return;if(demo){setStudents(p=>p.map(x=>x.id===s.id?{...x,status:'Arsip'}:x));return}const {error}=await client!.from('students').update({status:'Arsip'}).eq('id',s.id);if(error)flash(error.message);else void refresh()}
  async function invite(e:React.FormEvent){e.preventDefault();if(!membership||!user||!client)return;setBusy(true);const token=Array.from(crypto.getRandomValues(new Uint8Array(32)),x=>x.toString(16).padStart(2,'0')).join('');const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token));const token_hash=Array.from(new Uint8Array(bytes),x=>x.toString(16).padStart(2,'0')).join('');const {error}=await client.from('invitations').insert({school_id:membership.school_id,email:inviteEmail.trim().toLowerCase(),role:inviteRole,invited_by:user.id,token_hash});setBusy(false);if(error)flash(error.message);else{setInviteToken(token);flash('Kode undangan dibuat. Salin dan bagikan hanya kepada petugas yang dituju.')}}
  async function claimInvite(){if(!client||!user||!claimToken.trim())return;setBusy(true);const {data,error}=await client.rpc('claim_bk_invitation',{p_token:claimToken.trim()});setBusy(false);if(error)flash(error.message);else if(!data)flash('Kode undangan tidak cocok atau sudah dipakai.');else{setClaimToken('');void refresh();flash('Undangan diterima.')}}
  function exportStudents(){download('bk-pro-siswa.csv',csv(students.map(s=>({NIS:s.nis,Nama:s.name,Kelas:s.class_name,JK:s.gender,Wali:s.guardian_name,Kontak:s.guardian_phone,Status:s.status})),['NIS','Nama','Kelas','JK','Wali','Kontak','Status']))}
  async function importStudents(file:File){
    if(!membership||!client||busy)return
    setBusy(true)
    try{
      const text=await file.text()
      const lines=text.replace(/^\ufeff/,'').trim().split(/\r?\n/)
        .map(line=>line.match(/(?:"(?:[^"]|"")*"|[^,]*)(?:,|$)/g)?.map(x=>x.replace(/,$/,'').replace(/^"|"$/g,'').replaceAll('""','"'))||[])
      const headers=lines.shift()?.map(x=>x.trim().toLowerCase())||[]
      const get=(row:string[],aliases:string[])=>row[headers.findIndex(h=>aliases.includes(h))]||''
      const rows=lines.filter(row=>row.some(Boolean)).map(row=>({
        school_id:membership.school_id,
        nis:get(row,['nis','nisn']).trim(),
        name:get(row,['nama','nama siswa','name']).trim(),
        class_name:get(row,['kelas','class']).trim(),
        gender:get(row,['jk','jenis kelamin','gender'])||'L',
        guardian_name:get(row,['wali','nama orang tua/wali']),
        guardian_phone:get(row,['kontak','kontak wali (wa)']),
        status:'Aktif',counselor_id:user?.id||null
      })).filter(x=>x.nis&&x.name&&x.class_name&&['L','P'].includes(x.gender))
      if(!rows.length){flash('CSV harus memiliki kolom NIS, Nama, dan Kelas, serta JK L/P bila diisi.');return}
      const unique=new Map<string,typeof rows[number]>()
      for(const row of rows)if(!unique.has(row.nis))unique.set(row.nis,row)
      const duplicateInFile=rows.length-unique.size
      if(demo){
        const current=new Set(students.map(s=>s.nis))
        const fresh=[...unique.values()].filter(x=>!current.has(x.nis))
        setStudents(p=>[...p,...fresh.map(x=>({...x,id:uid(),created_at:new Date().toISOString()}))])
        flash(fresh.length+' siswa diimpor dalam demo; '+(rows.length-fresh.length)+' duplikat dilewati.')
        return
      }
      // Read the entire NIS index: never upsert and silently replace an existing student's profile.
      const existing=new Set<string>()
      let offset=0
      while(true){
        const {data,error}=await client.from('students').select('nis').eq('school_id',membership.school_id).range(offset,offset+999)
        if(error)throw error
        for(const x of data||[])existing.add(x.nis)
        if((data||[]).length<1000)break
        offset+=1000
      }
      const fresh=[...unique.values()].filter(x=>!existing.has(x.nis))
      if(!fresh.length){flash('Tidak ada siswa baru. '+rows.length+' baris sudah ada/duplikat; data lama tidak diubah.');return}
      let inserted=0
      for(let offset=0;offset<fresh.length;offset+=200){
        const {error}=await client.from('students').insert(fresh.slice(offset,offset+200))
        if(error)throw new Error(error.message+' ('+inserted+' siswa baru sudah tersimpan; periksa sebelum mengulangi impor)')
        inserted+=Math.min(200,fresh.length-offset)
      }
      await refresh()
      flash(inserted+' siswa baru diimpor. '+(duplicateInFile+(unique.size-fresh.length))+' duplikat dilewati; data lama tidak ditimpa.')
    }catch(e:any){flash(e?.message||'Impor gagal. Data siswa lama tidak diubah.')}
    finally{setBusy(false)}
  }
  const report=useMemo(()=>({total:remoteReport?.students??students.filter(s=>s.status==='Aktif').length,handled:remoteReport?.cases??cases.length,completed:remoteReport?.completed??cases.filter(c=>c.status==='Selesai').length,sessions:remoteReport?.sessions??records.filter(r=>r.kind==='counseling').length,service:remoteReport?.services??records.length,domain:domains.map(d=>({name:d,count:remoteReport?.domains?.[d]??cases.filter(c=>c.domain===d).length}))}),[students,cases,records,remoteReport])
  if(boot)return <div className="center-screen"><div className="loader"/>Memuat BK Pro…</div>
  if(!user&&!demo)return <div className="auth-shell"><div className="auth-story"><div className="brand"><img className="brand-logo" src="/bantu-beres-logo.png" alt="Logo Bantu Beres"/><span>Bantu Beres <strong>BK Pro</strong></span></div><div className="story-copy"><div className="eyebrow">RUANG KERJA BIMBINGAN & KONSELING</div><h1>Lebih dekat dengan siswa. Lebih rapi setiap tindak lanjut.</h1><p>Dari pemetaan kebutuhan hingga evaluasi layanan, semua tersusun dalam satu alur kerja yang aman untuk tim BK.</p><div className="story-points"><span><ShieldCheck size={19}/> Catatan sensitif terlindungi</span><span><Activity size={19}/> Perkembangan siswa terpantau</span></div></div><div className="story-footer">Bantu Beres · Ruang kerja sekolah yang lebih manusiawi</div></div><div className="auth-panel"><button className="theme-floating" onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?<Moon size={19}/>:<Sun size={19}/>}</button><div className="auth-card"><span className="small-tag">SELAMAT DATANG</span><h2>{client?(authMode==='login'?'Masuk ke BK Pro':'Buat akun BK Pro'):'Pratinjau BK Pro'}</h2><p>{client?'Akses ruang kerja sekolah Anda dengan akun yang terdaftar.':'Koneksi Supabase belum disetel. Jelajahi antarmuka dengan data contoh.'}</p>{client?<form onSubmit={auth} className="form-stack"><label>Email<input type="email" required value={authEmail} onChange={e=>setAuthEmail(e.target.value)} placeholder="nama@sekolah.sch.id"/></label><label>Kata sandi<input type="password" required minLength={authMode==='register'?8:6} value={authPassword} onChange={e=>setAuthPassword(e.target.value)} placeholder={authMode==='register'?"Minimal 8 karakter":"Kata sandi Anda"}/></label><button className="btn primary wide" disabled={busy}>{busy?'Memproses…':authMode==='login'?'Masuk ke workspace':'Daftar akun'} <ArrowRight size={17}/></button><button type="button" className="text-button" onClick={()=>setAuthMode(authMode==='login'?'register':'login')}>{authMode==='login'?'Belum punya akun? Daftar':'Sudah punya akun? Masuk'}</button></form>:<button className="btn primary wide" onClick={()=>{setDemo(true);setMembership({school_id:'demo',user_id:'demo',role:'owner',display_name:'Guru BK',school:{name:'Sekolah Demo',academic_year:'2026/2027'}})}}>Lihat mode demo <ArrowRight size={17}/></button>}<div className="auth-note"><LockKeyhole size={15}/> Akses khusus petugas sekolah yang berwenang.</div></div></div></div>
  if(!membership)return <div className="setup-shell"><div className="setup-card"><img className="brand-logo" src="/bantu-beres-logo.png" alt="Logo Bantu Beres"/><span className="small-tag">LANGKAH PERTAMA</span><h1>Siapkan ruang kerja sekolah</h1><p>Nama sekolah dan tahun ajaran menjadi dasar seluruh layanan BK Anda.</p><form onSubmit={createSchool} className="form-stack"><label>Nama sekolah<input required value={schoolName} onChange={e=>setSchoolName(e.target.value)} placeholder="Contoh: SMP Negeri 5 Sukamaju"/></label><label>Tahun ajaran<input required value={academicYear} onChange={e=>setAcademicYear(e.target.value)} placeholder="2026/2027"/></label><button disabled={busy} className="btn primary wide">Buat ruang kerja <ArrowRight size={17}/></button></form><div className="setup-divider">atau</div><label className="claim-label">Kode undangan dari admin sekolah<input value={claimToken} onChange={e=>setClaimToken(e.target.value)} placeholder="Tempel kode undangan" autoComplete="off"/></label><button className="btn secondary wide" disabled={busy||!claimToken.trim()} onClick={claimInvite}>Terima undangan sekolah</button><button className="text-button" onClick={()=>client?.auth.signOut()}>Keluar dari akun</button></div>{toast&&<div className="toast">{toast}</div>}</div>
  return <div className="app-shell">
    {sidebar&&<div className="scrim" onClick={()=>setSidebar(false)}/>}
    <aside className={`sidebar ${sidebar?'open':''}`}><div className="sidebar-head"><div className="brand"><img className="brand-logo" src="/bantu-beres-logo.png" alt="Logo Bantu Beres"/><span>Bantu Beres <strong>BK Pro</strong></span></div><button className="icon-btn mobile-only" onClick={()=>setSidebar(false)} aria-label="Tutup navigasi"><X size={20}/></button></div><div className="school-switch"><div className="school-icon"><GraduationCap size={19}/></div><div><strong>{school}</strong><small>Tahun ajaran {membership.school?.academic_year}</small></div><ChevronDown size={16}/></div><div className="nav-scroll">{nav.map(group=><div className="nav-group" key={group.title}><div className="nav-heading">{group.title}</div>{group.items.filter(([key])=>role!=='principal'||['dashboard','analytics','reports','settings'].includes(key)).map(([key,label,Icon])=><button className={`nav-item ${tab===key?'active':''}`} key={key} onClick={()=>{setTab(key);setSearch('');setSelected(null);setSidebar(false)}}><Icon size={18}/><span>{label}</span>{key==='followup'&&due>0&&<i>{due}</i>}</button>)}</div>)}</div><div className="sidebar-bottom"><div className="account-avatar">{membership.display_name.slice(0,1).toUpperCase()}</div><div><strong>{membership.display_name}</strong><small>{role==='owner'?'Admin sekolah':role==='counselor'?'Guru BK':role==='principal'?'Kepala sekolah':'Staf'}</small></div><button className="icon-btn" title="Keluar" onClick={()=>demo?setDemo(false):client?.auth.signOut()}><LogOut size={18}/></button></div></aside>
    <main className="main"><header className="topbar"><div className="top-left"><button className="icon-btn mobile-only" onClick={()=>setSidebar(true)} aria-label="Buka navigasi"><Menu size={21}/></button><div className="crumb">Workspace <span>/</span> <strong>{tabName}</strong></div></div><div className="top-actions"><span className="date-chip"><CalendarDays size={15}/>{dateLabel(today())}</span><button className="icon-btn" aria-label="Ganti tema" onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?<Moon size={19}/>:<Sun size={19}/>}</button><button className="icon-btn alert-btn" aria-label="Tindak lanjut jatuh tempo" onClick={()=>setTab(role==='principal'?'reports':'followup')}><Bell size={19}/>{role!=='principal'&&due>0&&<i/>}</button><span className="top-avatar">{membership.display_name.slice(0,1).toUpperCase()}</span></div></header>
    <div className="content">{demo&&<div className="demo-banner"><CircleHelp size={16}/> Mode demo: data hanya tersimpan selama halaman ini terbuka. Sambungkan Supabase untuk pemakaian sebenarnya.</div>}
      {tab==='dashboard'&&<><div className="hero-card"><div><span className="eyebrow">WORKSPACE BIMBINGAN & KONSELING</span><h1>Selamat datang, {membership.display_name.split(' ')[0]}.</h1><p>Setiap perhatian kecil dapat menjadi langkah besar untuk siswa. Mulai dari yang perlu ditindaklanjuti hari ini.</p>{canEdit&&<button className="btn white" onClick={()=>{setTab('cases');openNew('case')}}><Plus size={17}/> Catat kasus baru</button>}</div><div className="hero-art"><div className="hero-orbit"><HeartHandshake size={62} strokeWidth={1.3}/></div><span className="hero-spark one"/><span className="hero-spark two"/></div></div><div className="section-head"><div><span className="small-tag">RINGKASAN HARI INI</span><h2>Gambaran layanan</h2></div><span className="muted">Data tahun ajaran {membership.school?.academic_year}</span></div><div className="stat-grid"><Stat label="Siswa aktif" value={report.total} icon={<Users/>} tone="violet" description="Terdaftar di sekolah"/><Stat label="Kasus berjalan" value={role==='principal'?Math.max(0,report.handled-report.completed):activeCases.length} icon={<ShieldCheck/>} tone="orange" description="Butuh pemantauan"/><Stat label="Layanan tercatat" value={report.service} icon={<BookOpen/>} tone="blue" description="Semua jenis layanan"/>{role==='principal'?<Stat label="Sesi individu" value={report.sessions} icon={<HeartHandshake/>} tone="pink" description="Data agregat tanpa rincian sesi"/>:<Stat label="Jatuh tempo" value={due} icon={<CalendarDays/>} tone="pink" description="Perlu perhatian hari ini"/>}</div>{role!=='principal'&&<div className="dashboard-grid"><section className="panel"><div className="panel-heading"><div><h3>Kasus terbaru</h3><p>Ikuti perkembangan kasus yang sedang ditangani.</p></div><button className="subtle-link" onClick={()=>setTab('cases')}>Lihat semua <ArrowRight size={15}/></button></div>{cases.length?<div className="stack-list">{cases.slice(0,4).map(c=><div className="list-line" key={c.id}><span className="line-icon"><ShieldCheck size={18}/></span><div><strong>{idName(c.student_id,students)}</strong><small>{c.topic} · {dateLabel(c.opened_on)}</small></div><Pill label={c.status}/></div>)}</div>:<Empty message="Belum ada kasus. Catat kasus pertama untuk memulai."/>}</section><section className="panel"><div className="panel-heading"><div><h3>Akses cepat</h3><p>Langsung ke pekerjaan yang paling sering digunakan.</p></div></div><div className="quick-grid"><Quick icon={<Users/>} title="Tambah siswa" text="Lengkapi data dasar" onClick={()=>{setTab('students');openNew('student')}}/><Quick icon={<HeartHandshake/>} title="Catat konseling" text="Sesi dan tindak lanjut" onClick={()=>{setTab('counseling');openNew('record')}}/><Quick icon={<CalendarDays/>} title="Buat agenda" text="Jadwalkan layanan" onClick={()=>{setTab('agenda');openNew('record')}}/><Quick icon={<BarChart3/>} title="Lihat laporan" text="Ringkasan sekolah" onClick={()=>setTab('reports')}/></div></section></div>}</>}
      {tab==='students'&&<><PageTitle kicker="DATA SISWA" title="Siswa 360°" description="Satu profil untuk melihat layanan, kasus, dan perkembangan setiap siswa." action={canEdit?<button className="btn primary" onClick={()=>openNew('student')}><Plus size={17}/> Tambah siswa</button>:null}/><div className="toolbar"><div className="search-box"><Search size={18}/><input placeholder="Cari nama, NIS, atau kelas…" value={search} onChange={e=>setSearch(e.target.value)}/></div><select value={classFilter} onChange={e=>setClassFilter(e.target.value)}><option>Semua kelas</option>{classes.map(c=><option key={c}>{c}</option>)}</select><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option>Aktif</option><option>Arsip</option><option>Semua</option></select><button className="btn secondary" onClick={exportStudents}><Download size={16}/> Ekspor</button>{canEdit&&<><button className="btn secondary" onClick={()=>importRef.current?.click()}><Upload size={16}/> Impor CSV</button><input type="file" ref={importRef} accept=".csv,text/csv" hidden onChange={e=>{if(e.target.files?.[0])void importStudents(e.target.files[0]);e.target.value=''}}/></>}</div><div className="panel table-panel"><div className="table-caption"><strong>{shownStudents.length} siswa</strong><span>Klik siswa untuk melihat profil dan riwayatnya.</span></div><div className="table-wrap"><table><thead><tr><th>Siswa</th><th>NIS</th><th>Kelas</th><th>Wali</th><th>Status</th><th></th></tr></thead><tbody>{shownStudents.map(s=><tr key={s.id} onClick={()=>setSelected(s)}><td><div className="person"><span className="person-avatar">{s.name.slice(0,1)}</span><strong>{s.name}</strong></div></td><td>{s.nis}</td><td>{s.class_name}</td><td>{s.guardian_name||'—'}</td><td><Pill label={s.status}/></td><td><ArrowRight size={16}/></td></tr>)}</tbody></table></div>{!shownStudents.length&&<Empty message="Belum ada siswa sesuai filter. Tambahkan siswa atau impor CSV."/>}</div></>}
      {tab==='cases'&&<><PageTitle kicker="PENANGANAN KASUS" title="Kasus & asesmen" description="Alur kasus dari identifikasi hingga evaluasi dan status akhir." action={canEdit?<button className="btn primary" onClick={()=>openNew('case')}><Plus size={17}/> Kasus baru</button>:null}/><div className="toolbar"><div className="search-box"><Search size={18}/><input placeholder="Cari siswa, kode, topik…" value={search} onChange={e=>setSearch(e.target.value)}/></div><span className="toolbar-count">{activeCases.length} kasus berjalan</span></div><div className="case-grid">{visibleCases.map(c=><article className="case-card" key={c.id} onClick={()=>canEdit&&c.counselor_id===user?.id&&editCase(c)}><div className="case-top"><span className="case-code">{c.code}</span><Pill label={c.status}/></div><h3>{c.topic}</h3><div className="case-student"><span className="person-avatar mini">{idName(c.student_id,students).slice(0,1)}</span>{idName(c.student_id,students)} <span>· {students.find(s=>s.id===c.student_id)?.class_name}</span></div><div className="case-divider"/><div className="case-meta"><span>{c.domain} · {c.priority}</span><span>{dateLabel(c.opened_on)}</span></div>{c.next_on&&<div className="next-call">Tindak lanjut: {dateLabel(c.next_on)}</div>}</article>)}</div>{!visibleCases.length&&<div className="panel"><Empty message="Belum ada kasus. Buat kasus baru untuk mulai mencatat penanganan."/></div>}</>}
      {kinds.some(([key])=>key===tab)&&<><PageTitle kicker="CATATAN LAYANAN" title={tabName} description={tab==='counseling'?'Catatan sesi bersifat rahasia dan hanya dapat dibuka petugas berwenang.':'Rencanakan, catat, dan evaluasi kegiatan bimbingan konseling.'} action={canEdit?<button className="btn primary" onClick={()=>openNew('record')}><Plus size={17}/> Tambah catatan</button>:null}/><div className="toolbar"><div className="search-box"><Search size={18}/><input placeholder="Cari judul atau siswa…" value={search} onChange={e=>setSearch(e.target.value)}/></div><span className="toolbar-count">{visibleRecords.length} catatan</span></div><div className="panel table-panel"><div className="table-wrap"><table><thead><tr><th>Judul / topik</th><th>Siswa / sasaran</th><th>Tanggal</th><th>Bidang</th><th>Status</th><th></th></tr></thead><tbody>{visibleRecords.map(r=><tr key={r.id} onClick={()=>canEdit&&r.counselor_id===user?.id&&editRecord(r)}><td><strong>{r.title}</strong>{r.confidential&&<small className="confidential"><LockKeyhole size={12}/> Terbatas</small>}</td><td>{idName(r.student_id,students)}</td><td>{dateLabel(r.happened_on)}</td><td>{r.domain}</td><td><Pill label={r.status}/></td><td><ArrowRight size={16}/></td></tr>)}</tbody></table></div>{!visibleRecords.length&&<Empty message={`Belum ada catatan ${tabName.toLowerCase()}.`}/>}</div></>}
      {tab==='analytics'&&<><PageTitle kicker="POLA & PERKEMBANGAN" title="Analitik BK" description="Kenali kebutuhan siswa dari catatan layanan, tanpa membuka isi sesi rahasia."/><div className="stat-grid"><Stat label="Siswa aktif" value={report.total} icon={<Users/>} tone="violet" description="Basis peserta didik"/><Stat label="Kasus selesai" value={report.completed} icon={<Check/>} tone="blue" description="Dituntaskan"/><Stat label="Sesi individu" value={report.sessions} icon={<HeartHandshake/>} tone="orange" description="Konseling tercatat"/><Stat label="Layanan kelompok" value={report.service} icon={<BookOpen/>} tone="pink" description="Kelompok & klasikal"/></div><div className="panel chart-panel"><h3>Distribusi bidang kasus</h3><p className="muted">Jumlah kasus menurut bidang layanan.</p>{report.domain.map(item=><div className="bar-row" key={item.name}><strong>{item.name}</strong><div className="bar-track"><span style={{width:`${Math.max(item.count?5:0,item.count/Math.max(1,report.handled)*100)}%`}}/></div><b>{item.count}</b></div>)}</div></>}
      {tab==='reports'&&<><PageTitle kicker="LAPORAN SEKOLAH" title="Laporan BK" description="Ringkasan agregat untuk kepala sekolah, tanpa nama siswa atau isi sesi konseling." action={<button className="btn primary" onClick={()=>window.print()}><Download size={17}/> Cetak / simpan PDF</button>}/><section className="panel report-card"><div className="report-header"><img className="brand-logo small" src="/bantu-beres-logo.png" alt="Logo Bantu Beres"/><div><h2>Laporan layanan bimbingan & konseling</h2><p>{school} · Tahun ajaran {membership.school?.academic_year}</p></div></div><div className="report-metrics"><div><span>Siswa aktif</span><strong>{report.total}</strong></div><div><span>Total kasus</span><strong>{report.handled}</strong></div><div><span>Kasus selesai</span><strong>{report.completed}</strong></div><div><span>Layanan tercatat</span><strong>{report.service}</strong></div></div><h3>Bidang penanganan</h3>{report.domain.map(d=><div className="report-line" key={d.name}><span>{d.name}</span><strong>{d.count} kasus</strong></div>)}<p className="report-foot">Dibuat pada {dateLabel(today())}. Data individu dan isi konseling tidak disertakan.</p></section></>}
      {tab==='settings'&&<><PageTitle kicker="PENGATURAN" title="Ruang kerja sekolah" description="Informasi sekolah, akses tim, dan preferensi tampilan."/><div className="settings-grid"><section className="panel setting-card"><h3>Profil sekolah</h3><p className="muted">Data dasar ruang kerja aktif.</p><div className="setting-row"><span>Nama sekolah</span><strong>{school}</strong></div><div className="setting-row"><span>Tahun ajaran</span><strong>{membership.school?.academic_year}</strong></div><div className="setting-row"><span>Peran akun</span><strong>{role}</strong></div></section><section className="panel setting-card"><h3>Akses & tampilan</h3><p className="muted">Undang tim dan sesuaikan kenyamanan membaca.</p><div className="setting-row"><span>Tema tampilan</span><button className="btn secondary" onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?'Terang':'Gelap'} <Sun size={15}/></button></div>{isManager&&<div className="setting-row"><span>Guru BK / kepala sekolah</span><button className="btn secondary" onClick={()=>openNew('invite')}><Plus size={15}/> Undang petugas</button></div>}<div className="privacy-note"><LockKeyhole size={17}/> Kepala sekolah melihat ringkasan agregat. Catatan sesi sensitif dibatasi untuk guru BK yang menangani.</div></section></div></>}
    </div></main>
    {selected&&<div className="drawer-backdrop" onClick={()=>setSelected(null)}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><button className="icon-btn" onClick={()=>setSelected(null)}><ArrowLeft size={20}/></button><strong>Profil siswa</strong><button className="icon-btn" onClick={()=>setSelected(null)}><X size={20}/></button></div><div className="drawer-body"><div className="profile-hero"><span className="profile-avatar">{selected.name.slice(0,1)}</span><h2>{selected.name}</h2><span>{selected.class_name} · NIS {selected.nis}</span><Pill label={selected.status}/></div><div className="info-block"><h3>Informasi dasar</h3><div><span>Orang tua / wali</span><strong>{selected.guardian_name||'—'}</strong></div><div><span>Kontak wali</span><strong>{selected.guardian_phone||'—'}</strong></div></div><div className="info-block"><h3>Riwayat layanan</h3>{cases.filter(c=>c.student_id===selected.id).map(c=><div className="history-item" key={c.id}><span className="history-dot"/><div><strong>{c.topic}</strong><small>Kasus · {dateLabel(c.opened_on)} · {c.status}</small></div></div>)}{records.filter(r=>r.student_id===selected.id).map(r=><div className="history-item" key={r.id}><span className="history-dot"/><div><strong>{r.title}</strong><small>{kinds.find(k=>k[0]===r.kind)?.[1]} · {dateLabel(r.happened_on)}</small></div></div>)}{!cases.some(c=>c.student_id===selected.id)&&!records.some(r=>r.student_id===selected.id)&&<p className="muted">Belum ada riwayat layanan.</p>}</div>{canEdit&&<div className="drawer-actions"><button className="btn primary" onClick={()=>{setTab('cases');openNew('case');setSelected(null)}}><Plus size={16}/> Tambah kasus</button><button className="btn secondary" onClick={()=>editStudent(selected)}>Edit profil</button><button className="icon-btn" title="Arsipkan" onClick={()=>{void archiveStudent(selected);setSelected(null)}}><Archive size={18}/></button></div>}</div></aside></div>}
    {modal&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(null)}}><div className="modal-card"><div className="modal-head"><div><span className="small-tag">BK PRO</span><h2>{modal==='student'?(editId?'Edit data siswa':'Tambah siswa'):modal==='case'?(editId?'Edit kasus':'Kasus baru'):modal==='record'?(editId?'Edit catatan':`Tambah ${tabName.toLowerCase()}`):modal==='invite'?'Undang petugas':'Pengaturan sekolah'}</h2></div><button className="icon-btn" onClick={()=>setModal(null)}><X size={20}/></button></div>
      {modal==='student'&&<form onSubmit={saveStudent} className="modal-form"><div className="form-grid"><label>Nama siswa<input required value={studentForm.name} onChange={e=>setStudentForm({...studentForm,name:e.target.value})}/></label><label>NIS<input required value={studentForm.nis} onChange={e=>setStudentForm({...studentForm,nis:e.target.value})}/></label><label>Kelas<input required value={studentForm.class_name} onChange={e=>setStudentForm({...studentForm,class_name:e.target.value})} placeholder="VII-A"/></label><label>Jenis kelamin<select value={studentForm.gender} onChange={e=>setStudentForm({...studentForm,gender:e.target.value})}><option value="L">Laki-laki</option><option value="P">Perempuan</option></select></label><label>Nama orang tua / wali<input value={studentForm.guardian_name} onChange={e=>setStudentForm({...studentForm,guardian_name:e.target.value})}/></label><label>Kontak wali<input value={studentForm.guardian_phone} onChange={e=>setStudentForm({...studentForm,guardian_phone:e.target.value})}/></label><label>Status<select value={studentForm.status} onChange={e=>setStudentForm({...studentForm,status:e.target.value})}><option>Aktif</option><option>Arsip</option></select></label></div><FormActions busy={busy} close={()=>setModal(null)}/></form>}
      {modal==='case'&&<form onSubmit={saveCase} className="modal-form"><div className="form-grid"><label>Siswa<select required value={caseForm.student_id} onChange={e=>setCaseForm({...caseForm,student_id:e.target.value})}><option value="">Pilih siswa</option>{students.filter(s=>s.status==='Aktif').map(s=><option value={s.id} key={s.id}>{s.name} · {s.class_name}</option>)}</select></label><label>Tanggal identifikasi<input type="date" required value={caseForm.opened_on} onChange={e=>setCaseForm({...caseForm,opened_on:e.target.value})}/></label><label>Bidang<select value={caseForm.domain} onChange={e=>setCaseForm({...caseForm,domain:e.target.value})}>{domains.map(d=><option key={d}>{d}</option>)}</select></label><label>Urgensi<select value={caseForm.priority} onChange={e=>setCaseForm({...caseForm,priority:e.target.value})}><option>Rendah</option><option>Sedang</option><option>Tinggi</option><option>Mendesak</option></select></label><label className="full">Topik / masalah<input required value={caseForm.topic} onChange={e=>setCaseForm({...caseForm,topic:e.target.value})} placeholder="Ringkas dan objektif"/></label><label>Sumber informasi<input value={caseForm.source} onChange={e=>setCaseForm({...caseForm,source:e.target.value})} placeholder="Siswa, wali kelas, orang tua…"/></label><label>Status<select value={caseForm.status} onChange={e=>setCaseForm({...caseForm,status:e.target.value})}><option>Baru</option><option>Berjalan</option><option>Monitoring</option><option>Selesai</option><option>Arsip</option></select></label><label className="full">Ringkasan asesmen<textarea value={caseForm.summary} onChange={e=>setCaseForm({...caseForm,summary:e.target.value})} rows={3} placeholder="Catat seperlunya; hindari detail yang tidak diperlukan."/></label><label>Tanggal tindak lanjut<input type="date" value={caseForm.next_on} onChange={e=>setCaseForm({...caseForm,next_on:e.target.value})}/></label></div><FormActions busy={busy} close={()=>setModal(null)}/></form>}
      {modal==='record'&&<form onSubmit={saveRecord} className="modal-form"><div className="form-grid"><label className="full">Judul / topik<input required value={recordForm.title} onChange={e=>setRecordForm({...recordForm,title:e.target.value})} placeholder={`Topik ${tabName.toLowerCase()}`}/></label><label>Tanggal<input type="date" required value={recordForm.happened_on} onChange={e=>setRecordForm({...recordForm,happened_on:e.target.value})}/></label><label>Bidang<select value={recordForm.domain} onChange={e=>setRecordForm({...recordForm,domain:e.target.value})}>{domains.map(d=><option key={d}>{d}</option>)}</select></label><label>Siswa terkait (opsional)<select value={recordForm.student_id} onChange={e=>setRecordForm({...recordForm,student_id:e.target.value,case_id:''})}><option value="">Umum / kelompok</option>{students.filter(s=>s.status==='Aktif').map(s=><option key={s.id} value={s.id}>{s.name} · {s.class_name}</option>)}</select></label><label>Kasus terkait (opsional)<select value={recordForm.case_id} onChange={e=>setRecordForm({...recordForm,case_id:e.target.value})}><option value="">Tanpa kasus</option>{cases.filter(c=>c.student_id===recordForm.student_id).map(c=><option key={c.id} value={c.id}>{c.code} · {c.topic}</option>)}</select></label>{(fieldMap[tab]||[]).map(field=><label key={field.key}>{field.label}<input value={recordForm.details[field.key]||''} onChange={e=>setRecordForm({...recordForm,details:{...recordForm.details,[field.key]:e.target.value}})} placeholder={field.placeholder}/></label>)}<label>Status<select value={recordForm.status} onChange={e=>setRecordForm({...recordForm,status:e.target.value})}><option>Terencana</option><option>Berjalan</option><option>Selesai</option><option>Perlu tindak lanjut</option></select></label><label className="full">Catatan / hasil<textarea rows={4} value={recordForm.notes} onChange={e=>setRecordForm({...recordForm,notes:e.target.value})} placeholder="Hasil kegiatan, pengamatan, atau langkah berikutnya"/></label><label className="checkbox-label full"><input type="checkbox" checked={recordForm.confidential||tab==='counseling'||tab==='visit'} disabled={tab==='counseling'||tab==='visit'} onChange={e=>setRecordForm({...recordForm,confidential:e.target.checked})}/> Catatan rahasia, hanya dapat diakses konselor yang menangani</label></div><FormActions busy={busy} close={()=>setModal(null)}/></form>}
      {modal==='invite'&&<form onSubmit={invite} className="modal-form"><p className="muted">Buat kode undangan sekali pakai. Berikan hanya kepada rekan dengan email yang dituju.</p>{inviteToken?<div className="invite-code"><strong>Kode undangan sekali pakai</strong><code>{inviteToken}</code><button type="button" className="btn secondary" onClick={()=>navigator.clipboard.writeText(inviteToken)}>Salin kode</button><p>Kode ini hanya ditampilkan sekarang. Bagikan langsung kepada petugas yang dituju.</p></div>:<><div className="form-grid"><label className="full">Email petugas<input type="email" required value={inviteEmail} onChange={e=>setInviteEmail(e.target.value)} placeholder="guru@sekolah.sch.id"/></label><label className="full">Peran<select value={inviteRole} onChange={e=>setInviteRole(e.target.value)}><option value="counselor">Guru BK</option><option value="principal">Kepala sekolah (agregat)</option><option value="admin">Admin sekolah</option></select></label></div><FormActions busy={busy} close={()=>setModal(null)}/></>}</form>}
    </div></div>}
    {toast&&<div className="toast"><Check size={17}/>{toast}<button onClick={()=>setToast('')}><X size={15}/></button></div>}
  </div>
}

function Stat({label,value,icon,tone,description}:{label:string;value:number;icon:React.ReactNode;tone:string;description:string}){return <div className="stat-card"><div className={`stat-icon ${tone}`}>{icon}</div><span>{label}</span><strong>{value}</strong><small>{description}</small></div>}
function Pill({label}:{label:string}){const tone=['Selesai','Aktif'].includes(label)?'good':['Mendesak','Tinggi','Arsip'].includes(label)?'warn':'neutral';return <span className={`pill ${tone}`}>{label}</span>}
function Empty({message}:{message:string}){return <div className="empty"><div><ClipboardList size={23}/></div><strong>Belum ada data</strong><p>{message}</p></div>}
function Quick({icon,title,text,onClick}:{icon:React.ReactNode;title:string;text:string;onClick:()=>void}){return <button className="quick" onClick={onClick}><span>{icon}</span><strong>{title}</strong><small>{text}</small><ArrowRight size={16}/></button>}
function PageTitle({kicker,title,description,action}:{kicker:string;title:string;description:string;action?:React.ReactNode}){return <div className="page-title"><div><span className="small-tag">{kicker}</span><h1>{title}</h1><p>{description}</p></div>{action}</div>}
function FormActions({busy,close}:{busy:boolean;close:()=>void}){return <div className="form-actions"><button type="button" className="btn secondary" onClick={close}>Batal</button><button className="btn primary" disabled={busy}>{busy?'Menyimpan…':'Simpan data'} <Check size={16}/></button></div>}
